[2025-01-25T18:10:05.833+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-25T18:10:05.869+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extraction_by_hour_dag_v11.extract_and_load_to_mongodb_station_1 scheduled__2025-01-25T15:35:00+00:00 [queued]>
[2025-01-25T18:10:05.887+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extraction_by_hour_dag_v11.extract_and_load_to_mongodb_station_1 scheduled__2025-01-25T15:35:00+00:00 [queued]>
[2025-01-25T18:10:05.888+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-25T18:10:06.020+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_and_load_to_mongodb_station_1> on 2025-01-25 15:35:00+00:00
[2025-01-25T18:10:06.062+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'extraction_by_hour_dag_v11', 'extract_and_load_to_mongodb_station_1', 'scheduled__2025-01-25T15:35:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/extract_data_by_hour.py', '--cfg-path', '/tmp/tmp1fb5260j']
[2025-01-25T18:10:06.087+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=4923) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-01-25T18:10:06.092+0000] {standard_task_runner.py:105} INFO - Job 13: Subtask extract_and_load_to_mongodb_station_1
[2025-01-25T18:10:06.092+0000] {standard_task_runner.py:72} INFO - Started process 4929 to run task
[2025-01-25T18:10:06.333+0000] {task_command.py:467} INFO - Running <TaskInstance: extraction_by_hour_dag_v11.extract_and_load_to_mongodb_station_1 scheduled__2025-01-25T15:35:00+00:00 [running]> on host 64d28392d4c0
[2025-01-25T18:10:06.859+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extraction_by_hour_dag_v11' AIRFLOW_CTX_TASK_ID='extract_and_load_to_mongodb_station_1' AIRFLOW_CTX_EXECUTION_DATE='2025-01-25T15:35:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-25T15:35:00+00:00'
[2025-01-25T18:10:06.862+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-25T18:10:14.942+0000] {logging_mixin.py:190} INFO - Erreur pour la station 283164601 : HTTPSConnectionPool(host='airqino-api.magentalab.it', port=443): Max retries exceeded with url: /v3/getStationHourlyAvg/283164601 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fc68bdf9130>: Failed to resolve 'airqino-api.magentalab.it' ([Errno -3] Temporary failure in name resolution)"))
[2025-01-25T18:10:22.955+0000] {logging_mixin.py:190} INFO - Erreur pour la station 283181971 : HTTPSConnectionPool(host='airqino-api.magentalab.it', port=443): Max retries exceeded with url: /v3/getStationHourlyAvg/283181971 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fc68bcd40e0>: Failed to resolve 'airqino-api.magentalab.it' ([Errno -3] Temporary failure in name resolution)"))
[2025-01-25T18:10:22.963+0000] {logging_mixin.py:190} INFO - Aucune donnée valide récupérée pour la station 283164601.
[2025-01-25T18:10:22.964+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-25T18:10:23.268+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-25T18:10:23.269+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=extraction_by_hour_dag_v11, task_id=extract_and_load_to_mongodb_station_1, run_id=scheduled__2025-01-25T15:35:00+00:00, execution_date=20250125T153500, start_date=20250125T181005, end_date=20250125T181023
[2025-01-25T18:10:23.309+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-25T18:10:23.335+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-25T18:10:23.338+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
