[2025-01-26T00:37:33.388+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-26T00:37:33.465+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extraction_by_hour_dag_v11.extract_and_load_to_mongodb_station_1 manual__2025-01-26T00:37:31.243728+00:00 [queued]>
[2025-01-26T00:37:33.484+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extraction_by_hour_dag_v11.extract_and_load_to_mongodb_station_1 manual__2025-01-26T00:37:31.243728+00:00 [queued]>
[2025-01-26T00:37:33.484+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-26T00:37:33.507+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_and_load_to_mongodb_station_1> on 2025-01-26 00:37:31.243728+00:00
[2025-01-26T00:37:33.528+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'extraction_by_hour_dag_v11', 'extract_and_load_to_mongodb_station_1', 'manual__2025-01-26T00:37:31.243728+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/extract_data_by_hour.py', '--cfg-path', '/tmp/tmpo7wzi99w']
[2025-01-26T00:37:33.553+0000] {standard_task_runner.py:105} INFO - Job 36: Subtask extract_and_load_to_mongodb_station_1
[2025-01-26T00:37:33.553+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=230) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-01-26T00:37:33.555+0000] {standard_task_runner.py:72} INFO - Started process 233 to run task
[2025-01-26T00:37:33.715+0000] {task_command.py:467} INFO - Running <TaskInstance: extraction_by_hour_dag_v11.extract_and_load_to_mongodb_station_1 manual__2025-01-26T00:37:31.243728+00:00 [running]> on host 63b35b4cd871
[2025-01-26T00:37:33.986+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extraction_by_hour_dag_v11' AIRFLOW_CTX_TASK_ID='extract_and_load_to_mongodb_station_1' AIRFLOW_CTX_EXECUTION_DATE='2025-01-26T00:37:31.243728+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-26T00:37:31.243728+00:00'
[2025-01-26T00:37:33.989+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-26T00:38:16.264+0000] {logging_mixin.py:190} INFO - Erreur lors de l'insertion dans MongoDB : mongodb:27017: [Errno -3] Temporary failure in name resolution (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 679583dacfae8d5c15fd4f1d, topology_type: Unknown, servers: [<ServerDescription ('mongodb', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('mongodb:27017: [Errno -3] Temporary failure in name resolution (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>
[2025-01-26T00:38:16.274+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-26T00:38:16.286+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-26T00:38:16.287+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=extraction_by_hour_dag_v11, task_id=extract_and_load_to_mongodb_station_1, run_id=manual__2025-01-26T00:37:31.243728+00:00, execution_date=20250126T003731, start_date=20250126T003733, end_date=20250126T003816
[2025-01-26T00:38:16.336+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-26T00:38:16.357+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-26T00:38:16.360+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
