[2025-01-25T09:42:19.928+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-25T09:42:19.961+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extraction_by_hour_dag_v11.extract_and_load_to_mongodb_station_1 manual__2025-01-25T09:42:18.682442+00:00 [queued]>
[2025-01-25T09:42:19.978+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extraction_by_hour_dag_v11.extract_and_load_to_mongodb_station_1 manual__2025-01-25T09:42:18.682442+00:00 [queued]>
[2025-01-25T09:42:19.978+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-25T09:42:20.006+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_and_load_to_mongodb_station_1> on 2025-01-25 09:42:18.682442+00:00
[2025-01-25T09:42:20.026+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'extraction_by_hour_dag_v11', 'extract_and_load_to_mongodb_station_1', 'manual__2025-01-25T09:42:18.682442+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/extract_data_by_hour.py', '--cfg-path', '/tmp/tmp1x9ykw6_']
[2025-01-25T09:42:20.035+0000] {standard_task_runner.py:105} INFO - Job 8: Subtask extract_and_load_to_mongodb_station_1
[2025-01-25T09:42:20.038+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1153) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-01-25T09:42:20.039+0000] {standard_task_runner.py:72} INFO - Started process 1154 to run task
[2025-01-25T09:42:20.114+0000] {task_command.py:467} INFO - Running <TaskInstance: extraction_by_hour_dag_v11.extract_and_load_to_mongodb_station_1 manual__2025-01-25T09:42:18.682442+00:00 [running]> on host 64d28392d4c0
[2025-01-25T09:42:20.261+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extraction_by_hour_dag_v11' AIRFLOW_CTX_TASK_ID='extract_and_load_to_mongodb_station_1' AIRFLOW_CTX_EXECUTION_DATE='2025-01-25T09:42:18.682442+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-25T09:42:18.682442+00:00'
[2025-01-25T09:42:20.262+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-25T09:43:01.855+0000] {logging_mixin.py:190} INFO - Erreur lors de l'insertion dans MongoDB : mongodb:27017: [Errno -3] Temporary failure in name resolution (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 6794b20711705f093973957c, topology_type: Unknown, servers: [<ServerDescription ('mongodb', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('mongodb:27017: [Errno -3] Temporary failure in name resolution (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>
[2025-01-25T09:43:01.871+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-25T09:43:01.892+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-25T09:43:01.893+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=extraction_by_hour_dag_v11, task_id=extract_and_load_to_mongodb_station_1, run_id=manual__2025-01-25T09:42:18.682442+00:00, execution_date=20250125T094218, start_date=20250125T094219, end_date=20250125T094301
[2025-01-25T09:43:01.951+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-25T09:43:01.992+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-25T09:43:01.996+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
