[2025-01-25T23:12:19.128+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-25T23:12:19.144+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extraction_by_hour_dag_v11.extract_and_load_to_mongodb_station_2 manual__2025-01-25T23:12:18.506959+00:00 [queued]>
[2025-01-25T23:12:19.153+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extraction_by_hour_dag_v11.extract_and_load_to_mongodb_station_2 manual__2025-01-25T23:12:18.506959+00:00 [queued]>
[2025-01-25T23:12:19.153+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-25T23:12:19.166+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_and_load_to_mongodb_station_2> on 2025-01-25 23:12:18.506959+00:00
[2025-01-25T23:12:19.177+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'extraction_by_hour_dag_v11', 'extract_and_load_to_mongodb_station_2', 'manual__2025-01-25T23:12:18.506959+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/extract_data_by_hour.py', '--cfg-path', '/tmp/tmp0_9rek3z']
[2025-01-25T23:12:19.180+0000] {standard_task_runner.py:105} INFO - Job 30: Subtask extract_and_load_to_mongodb_station_2
[2025-01-25T23:12:19.181+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=341) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-01-25T23:12:19.181+0000] {standard_task_runner.py:72} INFO - Started process 343 to run task
[2025-01-25T23:12:19.226+0000] {task_command.py:467} INFO - Running <TaskInstance: extraction_by_hour_dag_v11.extract_and_load_to_mongodb_station_2 manual__2025-01-25T23:12:18.506959+00:00 [running]> on host 887b9580b76e
[2025-01-25T23:12:19.323+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extraction_by_hour_dag_v11' AIRFLOW_CTX_TASK_ID='extract_and_load_to_mongodb_station_2' AIRFLOW_CTX_EXECUTION_DATE='2025-01-25T23:12:18.506959+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-25T23:12:18.506959+00:00'
[2025-01-25T23:12:19.324+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-25T23:12:58.251+0000] {logging_mixin.py:190} INFO - Erreur lors de l'insertion dans MongoDB : mongodb:27017: [Errno -3] Temporary failure in name resolution (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 67956fdc4410e20bf5731045, topology_type: Unknown, servers: [<ServerDescription ('mongodb', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('mongodb:27017: [Errno -3] Temporary failure in name resolution (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>
[2025-01-25T23:12:58.258+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-25T23:12:58.268+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-25T23:12:58.269+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=extraction_by_hour_dag_v11, task_id=extract_and_load_to_mongodb_station_2, run_id=manual__2025-01-25T23:12:18.506959+00:00, execution_date=20250125T231218, start_date=20250125T231219, end_date=20250125T231258
[2025-01-25T23:12:58.322+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-25T23:12:58.340+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-25T23:12:58.342+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
