[2025-02-02T06:00:01.350+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-02T06:00:01.379+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extraction_by_hour_dag_v15.extract_and_load_to_mongodb_station_2 scheduled__2025-02-02T05:00:00+00:00 [queued]>
[2025-02-02T06:00:01.393+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extraction_by_hour_dag_v15.extract_and_load_to_mongodb_station_2 scheduled__2025-02-02T05:00:00+00:00 [queued]>
[2025-02-02T06:00:01.393+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-02-02T06:00:01.418+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_and_load_to_mongodb_station_2> on 2025-02-02 05:00:00+00:00
[2025-02-02T06:00:01.428+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'extraction_by_hour_dag_v15', 'extract_and_load_to_mongodb_station_2', 'scheduled__2025-02-02T05:00:00+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/extract_data_by_hour.py', '--cfg-path', '/tmp/tmpsjh6xud8']
[2025-02-02T06:00:01.432+0000] {standard_task_runner.py:105} INFO - Job 78: Subtask extract_and_load_to_mongodb_station_2
[2025-02-02T06:00:01.434+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=66911) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-02T06:00:01.435+0000] {standard_task_runner.py:72} INFO - Started process 66913 to run task
[2025-02-02T06:00:01.482+0000] {task_command.py:467} INFO - Running <TaskInstance: extraction_by_hour_dag_v15.extract_and_load_to_mongodb_station_2 scheduled__2025-02-02T05:00:00+00:00 [running]> on host 6f5fd3382d74
[2025-02-02T06:00:01.562+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extraction_by_hour_dag_v15' AIRFLOW_CTX_TASK_ID='extract_and_load_to_mongodb_station_2' AIRFLOW_CTX_EXECUTION_DATE='2025-02-02T05:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-02T05:00:00+00:00'
[2025-02-02T06:00:01.563+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-02T06:00:37.867+0000] {logging_mixin.py:190} INFO - Erreur lors de l'insertion dans MongoDB : localhost:27018: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 679f09e760edb2f054f27c9a, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27018) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27018: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>
[2025-02-02T06:00:37.878+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-02T06:00:37.892+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-02T06:00:37.893+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=extraction_by_hour_dag_v15, task_id=extract_and_load_to_mongodb_station_2, run_id=scheduled__2025-02-02T05:00:00+00:00, execution_date=20250202T050000, start_date=20250202T060001, end_date=20250202T060037
[2025-02-02T06:00:37.958+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-02T06:00:37.974+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-02T06:00:37.975+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
