[2025-02-02T18:00:00.735+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-02T18:00:00.760+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extraction_by_hour_dag_v19.extract_and_load_to_mongodb_station_1 scheduled__2025-02-02T17:00:00+00:00 [queued]>
[2025-02-02T18:00:00.778+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extraction_by_hour_dag_v19.extract_and_load_to_mongodb_station_1 scheduled__2025-02-02T17:00:00+00:00 [queued]>
[2025-02-02T18:00:00.778+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-02-02T18:00:00.805+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_and_load_to_mongodb_station_1> on 2025-02-02 17:00:00+00:00
[2025-02-02T18:00:00.823+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=7395) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-02T18:00:00.820+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'extraction_by_hour_dag_v19', 'extract_and_load_to_mongodb_station_1', 'scheduled__2025-02-02T17:00:00+00:00', '--job-id', '199', '--raw', '--subdir', 'DAGS_FOLDER/extract_data_by_hour.py', '--cfg-path', '/tmp/tmp_cf2blj0']
[2025-02-02T18:00:00.824+0000] {standard_task_runner.py:105} INFO - Job 199: Subtask extract_and_load_to_mongodb_station_1
[2025-02-02T18:00:00.824+0000] {standard_task_runner.py:72} INFO - Started process 7396 to run task
[2025-02-02T18:00:00.896+0000] {task_command.py:467} INFO - Running <TaskInstance: extraction_by_hour_dag_v19.extract_and_load_to_mongodb_station_1 scheduled__2025-02-02T17:00:00+00:00 [running]> on host a0bc887b90c4
[2025-02-02T18:00:01.031+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extraction_by_hour_dag_v19' AIRFLOW_CTX_TASK_ID='extract_and_load_to_mongodb_station_1' AIRFLOW_CTX_EXECUTION_DATE='2025-02-02T17:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-02T17:00:00+00:00'
[2025-02-02T18:00:01.032+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-02T18:11:53.691+0000] {logging_mixin.py:190} INFO - Erreur lors de l'insertion dans MongoDB : mymongodb:27017: [Errno -2] Name or service not known (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 679fb54afa29cc79fc52f611, topology_type: Unknown, servers: [<ServerDescription ('mymongodb', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('mymongodb:27017: [Errno -2] Name or service not known (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>
[2025-02-02T18:11:53.699+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-02T18:11:53.713+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-02T18:11:53.714+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=extraction_by_hour_dag_v19, task_id=extract_and_load_to_mongodb_station_1, run_id=scheduled__2025-02-02T17:00:00+00:00, execution_date=20250202T170000, start_date=20250202T180000, end_date=20250202T181153
[2025-02-02T18:11:53.772+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-02T18:11:53.792+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-02T18:11:53.800+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
